name: Update sights.json from Google Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download JSON from Google Sheets
        run: |
          curl -sL "https://script.googleusercontent.com/macros/echo?user_content_key=AehSKLjqfvXDNd-mdp7niUIpIXLKtmHbHv1jhZ4QFdiM8ov1BYF_c3qhbw0jGa0E3uHKyh5laDvmBa4WxgsZuGLL8rbQDd8F0v8aRGiwpNcAMlfMx3OlVevJGekl-xBu88JQ2IadRL87707OFmOs2AnwYBrbirG-PoJ_XBj4HXLv0VV4RmReDA7rBOTKsXbrWHEMn_45dYPe5exQqt_e_MkX3Ebcv8Z2KzM80UpnQwIC1EZYlyTZ4rDwZ67bq_q3XLVf3ZD5ohAhXNZ1fZy7ycLyROZ9IdkpLA&lib=MulQGqW6AXO4cswxVE0UK3PbtUGP9QdF0" -o sights.json

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sights.json
          git commit -m "Auto-update sights.json from Google Sheets" || echo "No changes to commit"
          git push
